### GET list all contratacao
GET http://localhost:8080/contratacao
Authorization: Bearer MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsqquFHu934IVJSeB0rOfWFu3cpUuSQM7C2RThh4k0KvZHaQTRfkmFk1B0zq4K1WRVaMzSrZIlvZdMMnIlKgNToXFTcW0VzaMLQ6Bc5TZUIu+HCJ5MDebSagzdzvWVWSeS8H/03xsB477Rgrb20WHlh30r1APX5BVxHFicQghUHDYiIrKlND7HOLZy8Gh8yWLkBCWPn2oShPWtQhaMw8GPuApsohZDLD28cwrbNU6pNtLgR0dKNKkq86uKzoye3otLsCNzi6zlaQq2NnJ+QjDQVCchRaOgkwxEE2Hn7ButlJJ1MWLnCtarpd5lOsenAfH6GvE1mtK0uoSTRMm8GUkSwIDAQAB
