### GET list all contratacao
GET http://localhost:8080/contratacao
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYW1wdXNnaWdzLWFwaSIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzg5NTk2Njk3LCJpYXQiOjE3ODk1OTYwOTd9.O_o6515H57yNBZU5kntKpQPs-11Pzln1fqQMeDDslCPaFZKzaNNyXc3BuG3M6WYl87lMyFJ_8I6owx4GQ1EWJ8yVs8jdbnnwPZkuQc1m5GHcFveYTQN_n7MLS1t5cDxariTAUJXnxONZRwYvIKwcJD1tkqZJrDmm1wyo5bxbuKzaOmARaa9fOwxLRCDvOukAniaWBkN1u7p2BvGuso-HY-ZXSSq2rZsKTbqT7RGQmUXa9OjblFDYmr8W822KfYG5kEB57tDlON1TdguT3z0lW39VOQKnlFldAlOvV4P2V5u0DETvkvwg_TTONmfIiyV5znT_sXPn6wEIWz0uqAbUkg

### GET list all usuario
GET http://localhost:8080/usuario
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYW1wdXNnaWdzLWFwaSIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzg5NTk2Njk3LCJpYXQiOjE3ODk1OTYwOTd9.O_o6515H57yNBZU5kntKpQPs-11Pzln1fqQMeDDslCPaFZKzaNNyXc3BuG3M6WYl87lMyFJ_8I6owx4GQ1EWJ8yVs8jdbnnwPZkuQc1m5GHcFveYTQN_n7MLS1t5cDxariTAUJXnxONZRwYvIKwcJD1tkqZJrDmm1wyo5bxbuKzaOmARaa9fOwxLRCDvOukAniaWBkN1u7p2BvGuso-HY-ZXSSq2rZsKTbqT7RGQmUXa9OjblFDYmr8W822KfYG5kEB57tDlON1TdguT3z0lW39VOQKnlFldAlOvV4P2V5u0DETvkvwg_TTONmfIiyV5znT_sXPn6wEIWz0uqAbUkg

### GET list all servico
GET http://localhost:8080/servico
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjYW1wdXNnaWdzLWFwaSIsInJvbGUiOiJVU0VSIiwiZXhwIjoxNzg5NTk2Njk3LCJpYXQiOjE3ODk1OTYwOTd9.O_o6515H57yNBZU5kntKpQPs-11Pzln1fqQMeDDslCPaFZKzaNNyXc3BuG3M6WYl87lMyFJ_8I6owx4GQ1EWJ8yVs8jdbnnwPZkuQc1m5GHcFveYTQN_n7MLS1t5cDxariTAUJXnxONZRwYvIKwcJD1tkqZJrDmm1wyo5bxbuKzaOmARaa9fOwxLRCDvOukAniaWBkN1u7p2BvGuso-HY-ZXSSq2rZsKTbqT7RGQmUXa9OjblFDYmr8W822KfYG5kEB57tDlON1TdguT3z0lW39VOQKnlFldAlOvV4P2V5u0DETvkvwg_TTONmfIiyV5znT_sXPn6wEIWz0uqAbUkg

