spring.application.name=CampusGigs

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.repair-on-migrate=true
spring.flyway.locations=classpath:db/migration


# RSA Keys (JWT)
rsa.private-key=classpath:keys/private_key.pem
rsa.public-key=classpath:keys/public_key.pem