-- usuario
CREATE TABLE usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100) NOT NULL,
    senha VARCHAR2(255) NOT NULL,
    email VARCHAR2(150) NOT NULL,
    role VARCHAR2(10) NOT NULL,

    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_role CHECK (role IN ('USER', 'ADMIN'))
);


-- Servico

CREATE TABLE servico (
   id NUMBER GENERATED BY DEFAULT AS IDENTITY,
   titulo VARCHAR2(150) NOT NULL,
   descricao VARCHAR2(500),
   categoria VARCHAR2(100),
   preco NUMBER(10,2),
   usuario_id NUMBER NOT NULL,
   situacao VARCHAR2(30),

   CONSTRAINT pk_servico PRIMARY KEY (id),
   CONSTRAINT fk_servico_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

-- Contratacao

CREATE TABLE contratacao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    servico_id NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    situacao VARCHAR2(30),

    CONSTRAINT pk_contratacao PRIMARY KEY (id),
    CONSTRAINT fk_contratacao_servico FOREIGN KEY (servico_id) REFERENCES servico(id),
    CONSTRAINT fk_contratacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
    CONSTRAINT uk_contratacao_servico UNIQUE (servico_id)
);

-- Índices para Foreign Keys

CREATE INDEX idx_servico_usuario
    ON servico(usuario_id);

CREATE INDEX idx_contratacao_servico
    ON contratacao(servico_id);

CREATE INDEX idx_contratacao_usuario
    ON contratacao(usuario_id);